security:
    firewalls:
        rsa_secured:
            pattern:   ^/
            rsa_auth:  true
            logout:
                path: /arena-auth-logout
                success_handler: neevalt.arena-auth-bundle.arena_auth_logout_handler
    providers:
        main:
            id: neevalt.arena-auth-bundle.arena_auth_user_provider